sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t wafflezgawd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wafflezgawd/docker-react npm run test